spring:
  application:
    name: data-read
  profiles.active: development

---
spring:
  config:
    activate:
      on-profile:
        - development
zshop.db:
  url: jdbc:mysql:// url: jdbc:mysql://
  username: root
  password: password
  driverClassName: com.mysql.jdbc.Driver

  
server:
  port: 4001
  servlet:
    context-path: "/${spring.application.name}"
 
---
spring:
  config:
    activate:
      on-profile:
        - uat
zshop.db:
  url: jdbc:mysql:// url: jdbc:mysql://
  username: root
  password: password
  driverClassName: com.mysql.jdbc.Driver
  
  
server:
  port: 4001
  servlet:
    context-path: "/${spring.application.name}"
---
spring:
  config:
    activate:
      on-profile:
        - production
  
zshop.db:
  url: jdbc:mysql:// url: jdbc:mysql://
  username: root
  password: password
  driverClassName: com.mysql.jdbc.Driver
              
  
server:
  port: 4001
  servlet:
    context-path: "/${spring.application.name}"
---
spring:
  config:
    activate:
      on-profile:
        - docker
        
zshop.db:
  url: jdbc:mysql:// url: jdbc:mysql://
  username: root
  password: password
  driverClassName: com.mysql.jdbc.Driver
          
  
server:
  port: 4001
  servlet:
    context-path: "/${spring.application.name}"
